### ISSUE TITLE
Add testsuite for !rahash2

### ISSUE THREAD

**Issue by radare** [radare/radare2-regressions#150]
https://github.com/radare/radare2-regressions/wiki/rahash2
- [x] -h Usage: rahash2 [-rBhLkv] [-b sz] [-a algo] [-s str] [-f from] [-t to] [file] ...
- [x]  -a algo     comma separated list of algorithms (default is 'sha256')
- [x]  -b bsize    specify the size of the block (instead of full file)
- [ ]  -B          show per-block hash 
- [x]  -c
- [x]  -e          swap endian (use little endian)
- [x]  -d / -D     encode/decode base64 string (-s) or file to stdout
- [x]  -f from     start hashing at given address
  - [x]  On a String
  - [x]  On a Hexpair
  - [x]  On a File
  - [x]  On "-"
- [x]  -i num      repeat hash N iterations
- [ ]  -S seed     use given seed (hexa or s:string) use ^ to prefix
- [x]  -k          show hash using the openssh's randomkey algorithm
- [x]  -q          run in quiet mode (only show results)
- [x]  -L          list all available algorithms (see -a)
- [x]  -r          output radare commands
- [x]  -s string   hash this string instead of files
- [x]  -t to       stop hashing at given address
  - [x]  On a String
  - [x]  On a Hexpair
  - [x]  On a File
  - [x]  On "-"
- [x]  -x hexstr   hash this hexpair string instead of files
- [x]  -v          show version information

Need also double check on some other tools or manual verification for those algorithm:
- [ ] crc16
- [ ] xor
- [ ] xorpair
- [ ] parity
- [ ] hamdist
- [ ] pcprint
- [ ] mod255
- [ ] xxhash

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/tree/master/t.tools/rahash2

Some tests already exists

**Comment by radare** [comment]
i did some changes in rahash2 -Bb, please someone verify them again in order to write some trustful tests on top of it. previous versions of rahash2 displayed wrong offsets in from-to ranges, which may confuse the reader.

**Comment by Maijin** [comment]
* [ ] (-h) Usage: rahash2 [-rBhLkv] [-b sz] [-a algo] [-s str] [-f from] [-t to] [file] ...
* [ ]  -a algo     comma separated list of algorithms (default is 'sha256')
* [ ]  -b bsize    specify the size of the block (instead of full file)
* [ ]  -B          show per-block hash
* [ ]  -e          swap endian (use little endian)
* [ ]  -d / -D     encode/decode base64 string (-s) or file to stdout
* [ ]  -f from     start hashing at given address
* [ ]  -i num      repeat hash N iterations
* [ ]  -S seed     use given seed (hexa or s:string) use ^ to prefix
* [ ]  -k          show hash using the openssh's randomkey algorithm
* [ ]  -q          run in quiet mode (only show results)
* [ ]  -L          list all available algorithms (see -a)
* [ ]  -r          output radare commands
* [ ]  -s string   hash this string instead of files
* [ ]  -t to       stop hashing at given address
* [ ]  -x hexstr   hash this hexpair string instead of files
* [ ]  -v          show version information

**Comment by radare** [comment]
The -f and -t flags must be tested against a file and -s string and -x hexpair too.

also, if source file is "-" it will slurp the contents from stdin. this must be tested too

**Comment by Maijin** [comment]
ok

**Comment by Maijin** [comment]
Existing tests of `#` here https://github.com/radare/radare2-regressions/tree/master/t/hash

**Comment by Maijin** [comment]
-b -S -k left

**Comment by stanciuadrian** [comment]
Please add -c checkbox, will implement soon.

**Comment by Maijin** [comment]
done

**Comment by radare** [comment]
Cool! btw, we should probably change that milestone :P

**Comment by Maijin** [comment]
Most of this is done, I was waiting on this to continue https://github.com/radare/radare2/issues/3274

**Comment by stanciuadrian** [comment]
I'll leave this here for future reference: http://www.di-mgt.com.au/sha_testvectors.html

**Comment by Maijin** [comment]
Done.
